# Generated by Django 5.1.6 on 2025-03-07 19:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("GameID", models.IntegerField(primary_key=True, serialize=False)),
                ("GameName", models.CharField(default="My Online Game", max_length=20)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                (
                    "Maxplayers",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(10)]
                    ),
                ),
                ("StartCash", models.IntegerField(default=3000)),
                ("Smallblind", models.IntegerField(default=10)),
                ("Raiseblind", models.IntegerField(default=8)),
                ("Timeout", models.IntegerField(default=5)),
                ("delay", models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cash", models.IntegerField(default=3000)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="Game.game",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
