# Generated by Django 5.1.6 on 2025-03-07 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Game", "0002_remove_player_game_player_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="Maxplayers",
            field=models.IntegerField(
                default=10, validators=[django.core.validators.MaxValueValidator(10)]
            ),
        ),
    ]
